# Generated by Django 2.0.2 on 2018-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crimedata',
            fields=[
                ('crime_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('day', models.CharField(max_length=3)),
                ('crime_code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=12)),
                ('weapon', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=32)),
                ('neighborhood', models.CharField(max_length=25)),
                ('premise', models.CharField(max_length=10)),
                ('inside_outside', models.CharField(max_length=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
