# Generated by Django 2.0.2 on 2018-04-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180415_1948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apicrimedata',
            table='api_CrimeData',
        ),
        migrations.AlterModelTable(
            name='crimedata',
            table='CrimeData',
        ),
    ]
