# Generated by Django 2.0.2 on 2018-04-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180415_1958'),
        ('api', '0002_auto_20180415_2008'),
    ]

    operations = [
    ]
