# Generated by Django 2.0.2 on 2018-04-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20180416_0055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apicrimedata',
            table='api_CrimeData',
        ),
    ]
