# Generated by Django 2.0.2 on 2018-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180416_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localvisualization',
            fields=[
                ('local_filter_id', models.IntegerField(db_column='local_filter_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('date_hidden', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('inside_outside', models.IntegerField(blank=True, null=True)),
                ('weapon', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=160, null=True)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('start_lon', models.FloatField(blank=True, null=True)),
                ('end_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'localvisualization',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='apicrimedata',
            table='api_crimedata',
        ),
        migrations.AlterModelTable(
            name='crimedata',
            table='crimedata',
        ),
    ]
